use std::path::{Path, PathBuf};
use tauri::AppHandle;
use tauri_plugin_dialog::{DialogExt, MessageDialogButtons, MessageDialogKind};

// ADR-014, Phase 3 — signed offline license verification. Runs as the very
// first step of bootstrap_and_launch (see offline/mod.rs), before Postgres
// or the Next.js server are touched, per the plan: an unlicensed install
// should never reach app functionality, not even the setup wizard.
//
// DEV KEY — generated by scripts/generate-offline-license.mjs for building
// and testing this flow. This is NOT the production key: the operator must
// run that script themselves to generate a real keypair, keep the private
// key outside this repo, and replace this constant (and mobile's identical
// copy in apps/mobile/src/lib/license.ts) before issuing any real licenses.
// Regenerating the key invalidates every license signed with the old one.
const OFFLINE_LICENSE_PUBLIC_KEY: [u8; 32] = [
    52, 251, 107, 174, 56, 0, 124, 228, 252, 255, 240, 241, 218, 7, 132, 22, 2, 164, 59, 79, 141,
    85, 69, 192, 227, 67, 248, 161, 39, 243, 173, 240,
];

const LICENSE_FILE_NAME: &str = "license.ptlicense";

#[derive(serde::Deserialize)]
struct LicenseEnvelope {
    version: u32,
    payload: String,
    signature: String,
}

/// Mirrors apps/mobile/src/lib/license.ts's LicensePayload exactly — both
/// verify the same envelope format produced by
/// scripts/generate-offline-license.mjs's `sign` command. Not every field is
/// consumed yet (no "About this license" UI exists), same as any DTO that
/// carries more than today's callers happen to read.
#[derive(serde::Deserialize, Clone)]
#[allow(dead_code)]
pub struct LicensePayload {
    #[serde(rename = "licenseId")]
    pub license_id: String,
    #[serde(rename = "pharmacyName")]
    pub pharmacy_name: String,
    #[serde(rename = "issuedAt")]
    pub issued_at: String,
    #[serde(rename = "expiresAt")]
    pub expires_at: Option<String>,
}

/// No hex crate needed for 32/64-byte fixed-length keys/signatures — this is
/// small enough to hand-roll and keeps the dependency list minimal.
fn decode_hex(s: &str) -> Result<Vec<u8>, String> {
    let s = s.trim();
    if s.len() % 2 != 0 {
        return Err("Corrupt license signature (odd-length hex)".to_string());
    }
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).map_err(|_| "Corrupt license signature (invalid hex)".to_string()))
        .collect()
}

fn verify_license_str(raw: &str) -> Result<LicensePayload, String> {
    let envelope: LicenseEnvelope =
        serde_json::from_str(raw).map_err(|e| format!("Not a valid license file: {e}"))?;
    if envelope.version != 1 {
        return Err(format!("Unsupported license file version {}", envelope.version));
    }

    let sig_bytes = decode_hex(&envelope.signature)?;
    let sig_array: [u8; 64] = sig_bytes
        .try_into()
        .map_err(|_| "Corrupt license signature (wrong length)".to_string())?;
    let signature = ed25519_dalek::Signature::from_bytes(&sig_array);

    let verifying_key = ed25519_dalek::VerifyingKey::from_bytes(&OFFLINE_LICENSE_PUBLIC_KEY)
        .map_err(|e| format!("Invalid embedded public key: {e}"))?;
    verifying_key
        .verify_strict(envelope.payload.as_bytes(), &signature)
        .map_err(|_| "License signature does not match — the file is invalid or was tampered with".to_string())?;

    serde_json::from_str(&envelope.payload).map_err(|e| format!("Corrupt license payload: {e}"))
}

fn stored_license_path(data_dir: &Path) -> PathBuf {
    data_dir.join(LICENSE_FILE_NAME)
}

/// Verifies a previously-accepted license is still present and valid, or
/// prompts for one via a native file-picker dialog — no webview/Next.js
/// needed at this point, deliberately, since this must gate everything else.
/// Re-verifies the signature on every call (not just first run): a cached
/// "already licensed" boolean would be trivial to fake by editing local
/// state, whereas the signature check itself is the actual guard.
///
/// Blocking — called from bootstrap_and_launch on its background thread.
pub fn ensure_licensed(app: &AppHandle, data_dir: &Path) -> Result<LicensePayload, String> {
    let stored_path = stored_license_path(data_dir);

    if stored_path.exists() {
        if let Ok(raw) = std::fs::read_to_string(&stored_path) {
            match verify_license_str(&raw) {
                Ok(payload) => return Ok(payload),
                Err(err) => eprintln!("[offline] stored license failed verification, re-prompting: {err}"),
            }
        }
    }

    loop {
        let picked = app
            .dialog()
            .file()
            .add_filter("PharmaTrack license", &["ptlicense"])
            .set_title("Select your PharmaTrack offline license file")
            .blocking_pick_file();

        let Some(picked) = picked else {
            app.dialog()
                .message("PharmaTrack Offline Edition requires a valid license file to run. The app will now close.")
                .title("License required")
                .kind(MessageDialogKind::Error)
                .blocking_show();
            return Err("No license file selected".to_string());
        };
        let picked_path = picked
            .into_path()
            .map_err(|e| format!("Invalid file selection: {e}"))?;

        let raw = std::fs::read_to_string(&picked_path)
            .map_err(|e| format!("Could not read license file: {e}"))?;

        match verify_license_str(&raw) {
            Ok(payload) => {
                std::fs::write(&stored_path, &raw).map_err(|e| format!("Could not save license: {e}"))?;
                return Ok(payload);
            }
            Err(err) => {
                let try_again = app
                    .dialog()
                    .message(format!("{err}\n\nSelect a different file?"))
                    .title("Invalid license file")
                    .kind(MessageDialogKind::Error)
                    .buttons(MessageDialogButtons::OkCancelCustom(
                        "Try again".to_string(),
                        "Quit".to_string(),
                    ))
                    .blocking_show();
                if !try_again {
                    return Err(err);
                }
            }
        }
    }
}
