-- migrate:up
-- Real Nairobi-pharmacy catalogue (normalized from Pharmacy_Inventory_Enriched.xlsx
-- via scripts/gen_catalog_seed.py): strength/form derived from item names, units
-- mapped, generic_name (molecule) derived for related-products grouping, deduped
-- on (name,strength,dosage_form). Prices are rough reference values to review.
-- Upsert is FK-safe: matching rows are updated in place (ids preserved), so any
-- product.catalog_id references stay intact.

INSERT INTO drug_catalog
  (name, brand_name, strength, dosage_form, base_unit, generic_name, category,
   is_controlled, requires_prescription, is_otc,
   default_cost_price, default_selling_price, default_pack_label, default_units_per_pack)
VALUES
('Activated charcoal', NULL, NULL, 'Syrup', 'bottle', 'activated charcoal', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Allugel', NULL, NULL, 'Syrup', 'bottle', 'antacid', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Alluicid susp', NULL, NULL, 'Syrup', 'bottle', 'alluicid', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Ashtons powder', NULL, NULL, 'Powder', 'bottle', 'ashtons', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Bisacodyl', 'Dulcolax', '5mg', 'Tablet', 'tablet', 'bisacodyl', 'Antacids & GI', false, false, true, 3.0, 8.0, 'Strip of 10', 10),
('Catoxynag', NULL, NULL, 'Syrup', 'bottle', 'catoxynag', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Cipladon', NULL, '500mg', 'Tablet', 'tablet', 'cipladon', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Cital 100ml', NULL, NULL, NULL, 'packet', 'cital', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Cofrid tabs', NULL, NULL, 'Tablet', 'tablet', 'cofrid', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Diracip M 100mls', NULL, NULL, 'Syrup', 'bottle', 'antacid', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Domperidone susp', 'Motilium', '10mg', 'Syrup', 'bottle', 'domperidone', 'Antacids & GI', false, false, true, 3.0, 8.0, 'Strip of 10', 10),
('Domperidone tabs', 'Motilium', '10mg', 'Tablet', 'tablet', 'domperidone', 'Antacids & GI', false, false, true, 3.0, 8.0, 'Strip of 10', 10),
('Eno sachets', 'Eno', NULL, 'Sachet', 'piece', 'eno sachets', 'Antacids & GI', false, false, true, 8.0, 20.0, 'Sachet', 1),
('Eno tablets', 'Eno', NULL, 'Sachet', 'tablet', 'eno tablets', 'Antacids & GI', false, false, true, 8.0, 20.0, 'Sachet', 1),
('Entamaxin 100mls', NULL, NULL, 'Syrup', 'bottle', 'entamaxin', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Entamaxin 60mls', NULL, NULL, 'Syrup', 'bottle', 'entamaxin', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Enterozole 100mls', NULL, NULL, 'Syrup', 'bottle', 'metronidazole+furazolidone', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Esomeprazole', 'Nexium', '20mg', 'Tablet', 'tablet', 'esomeprazole', 'Antacids & GI', false, true, false, 12.0, 25.0, 'Strip of 10', 10),
('Esomeprazole', 'Nexium', '40mg', 'Tablet', 'tablet', 'esomeprazole', 'Antacids & GI', false, true, false, 12.0, 25.0, 'Strip of 10', 10),
('Flagyl', 'Flagyl', '200mg', 'Tablet', 'tablet', 'metronidazole', 'Antacids & GI', false, true, false, 1.0, 3.0, 'Strip of 10', 10),
('Flagyl', 'Flagyl', '400mg', 'Tablet', 'tablet', 'metronidazole', 'Antacids & GI', false, true, false, 1.0, 3.0, 'Strip of 10', 10),
('Flagyl susp 60mls', 'Flagyl', '200mg', 'Syrup', 'bottle', 'metronidazole', 'Antacids & GI', false, true, false, 1.0, 3.0, 'Strip of 10', 10),
('Flatameal', NULL, NULL, 'Syrup', 'bottle', 'flatameal', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Gastrogel', NULL, NULL, 'Syrup', 'bottle', 'antacid', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Gaviscon double', 'Gaviscon', NULL, 'Suspension', 'bottle', 'gaviscon double', 'Antacids & GI', false, false, true, 220.0, 420.0, 'Bottle 200ml', 1),
('Gaviscon liquid', 'Gaviscon', NULL, 'Suspension', 'bottle', 'gaviscon liquid', 'Antacids & GI', false, false, true, 220.0, 420.0, 'Bottle 200ml', 1),
('Good morning tabs', NULL, NULL, 'Tablet', 'tablet', 'good morning', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Gripe water 100mls', NULL, NULL, 'Syrup', 'bottle', 'gripe water', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Gripe water 60mls', NULL, NULL, 'Syrup', 'bottle', 'gripe water', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Hyoscine suspension', 'Buscopan', '10mg', 'Syrup', 'bottle', 'hyoscine', 'Antacids & GI', false, false, true, 4.0, 10.0, 'Strip of 10', 10),
('Hyoscine tabs', 'Buscopan', '10mg', 'Tablet', 'tablet', 'hyoscine', 'Antacids & GI', false, false, true, 4.0, 10.0, 'Strip of 10', 10),
('Kahluma tabs', NULL, NULL, 'Tablet', 'tablet', 'kahluma', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Lactulose', 'Duphalac', NULL, 'Syrup', 'bottle', 'lactulose', 'Antacids & GI', false, false, true, 250.0, 450.0, 'Bottle 200ml', 1),
('Liquid paraffin', NULL, NULL, 'Syrup', 'bottle', 'liquid paraffin', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Loperamide caps', 'Imodium', '2mg', 'Capsule', 'packet', 'loperamide', 'Antacids & GI', false, false, true, 3.0, 8.0, 'Strip of 6', 6),
('Neutricid susp', NULL, NULL, 'Syrup', 'bottle', 'antacid', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Neutricid tabs', NULL, NULL, 'Tablet', 'tablet', 'antacid', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Nosic tabs', NULL, NULL, 'Tablet', 'tablet', 'nosic', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('ORS DTZ', 'ORS', NULL, 'Sachet', 'piece', 'ors dtz', 'Antacids & GI', false, false, true, 8.0, 20.0, 'Sachet', 1),
('ORS Sachets', 'ORS', NULL, 'Sachet', 'bottle', 'ors sachets', 'Antacids & GI', false, false, true, 8.0, 20.0, 'Sachet', 1),
('Omeprazole caps', NULL, '20mg', 'Capsule', 'capsule', 'omeprazole', 'Antacids & GI', false, false, true, 2.0, 6.0, 'Strip of 10', 10),
('Ondansetron tabs', 'Zofran', '4mg', 'Tablet', 'tablet', 'ondansetron', 'Antacids & GI', false, true, false, 8.0, 18.0, 'Strip of 10', 10),
('Pantoprazole', NULL, '40mg', 'Tablet', 'tablet', 'pantoprazole', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Plasil', 'Plasil', '10mg', 'Tablet', 'tablet', 'metoclopramide', 'Antacids & GI', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Plasil susp', 'Plasil', '10mg', 'Syrup', 'bottle', 'metoclopramide', 'Antacids & GI', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Prednisolone syrup', NULL, '100mg', 'Syrup', 'bottle', 'prednisolone', 'Antacids & GI', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Promethazine syrup', NULL, '100mg', 'Syrup', 'bottle', 'promethazine', 'Antacids & GI', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Promethazine tabs', 'Phenergan', '25mg', 'Tablet', 'tablet', 'promethazine', 'Antacids & GI', false, false, true, 2.0, 5.0, 'Strip of 10', 10),
('Rabeprazole', NULL, '20mg', 'Tablet', 'tablet', 'rabeprazole', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Relcer gel 100mls', NULL, NULL, 'Gel', 'bottle', 'antacid', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Relcer gel 180ML', NULL, NULL, 'Gel', 'bottle', 'antacid', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Remidin mouthwash', NULL, NULL, 'Solution', 'bottle', 'remidin mouthwash', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Secnidazole', NULL, NULL, 'Tablet', 'tablet', 'secnidazole', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Sonatec mouthwash', NULL, NULL, 'Solution', 'bottle', 'sonatec mouthwash', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Tinidazole', NULL, '500mg', 'Tablet', 'capsule', 'tinidazole', 'Antacids & GI', false, true, false, 6.0, 14.0, 'Strip of 10', 10),
('Touch and go', NULL, NULL, 'Sachet', 'sachet', 'touch and go', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Ulglcid', NULL, NULL, 'Syrup', 'bottle', 'ulglcid', 'Antacids & GI', false, false, true, NULL, NULL, NULL, 1),
('Zinc sulphate', NULL, '20mg', 'Tablet', 'tablet', 'zinc sulphate', 'Antacids & GI', false, false, true, 1.5, 4.0, 'Strip of 10', 10),
('Amoxicillin 100mls', NULL, '250mg', 'Capsule', 'bottle', 'amoxicillin', 'Antibiotics & Antifungals', false, true, false, 3.0, 7.0, 'Strip of 10', 10),
('Amoxicillin', NULL, '250mg', 'Capsule', 'capsule', 'amoxicillin', 'Antibiotics & Antifungals', false, true, false, 3.0, 7.0, 'Strip of 10', 10),
('Amoxicillin', NULL, '400mg', 'Capsule', 'capsule', 'amoxicillin', 'Antibiotics & Antifungals', false, true, false, 3.0, 7.0, 'Strip of 10', 10),
('Amoxicillin', NULL, '500mg', 'Capsule', 'capsule', 'amoxicillin', 'Antibiotics & Antifungals', false, true, false, 3.0, 7.0, 'Strip of 10', 10),
('Amoxicillin 60mls', NULL, '250mg', 'Capsule', 'bottle', 'amoxicillin', 'Antibiotics & Antifungals', false, true, false, 3.0, 7.0, 'Strip of 10', 10),
('Amoxiclav', NULL, '1g', NULL, 'packet', 'amoxicillin+clavulanate', 'Antibiotics & Antifungals', false, true, false, NULL, NULL, NULL, 1),
('Amoxiclav', NULL, '228.5mg', 'Syrup', 'bottle', 'amoxicillin+clavulanate', 'Antibiotics & Antifungals', false, true, false, NULL, NULL, NULL, 1),
('Amoxiclav', NULL, '457.5mg', NULL, 'packet', 'amoxicillin+clavulanate', 'Antibiotics & Antifungals', false, true, false, NULL, NULL, NULL, 1),
('Amoxiclav', NULL, '625mg', 'Tablet', 'tablet', 'amoxicillin+clavulanate', 'Antibiotics & Antifungals', false, true, false, NULL, NULL, NULL, 1),
('Ampiclox 100mls', 'Ampiclox', '500mg', 'Capsule', 'bottle', 'ampicillin+cloxacillin', 'Antibiotics & Antifungals', false, true, false, 5.0, 12.0, 'Strip of 10', 10),
('Ampiclox', 'Ampiclox', '500mg', 'Capsule', 'capsule', 'ampicillin+cloxacillin', 'Antibiotics & Antifungals', false, true, false, 5.0, 12.0, 'Strip of 10', 10),
('Ampiclox 60mls', 'Ampiclox', '500mg', 'Capsule', 'bottle', 'ampicillin+cloxacillin', 'Antibiotics & Antifungals', false, true, false, 5.0, 12.0, 'Strip of 10', 10),
('Augmentin', 'Augmentin', '625mg', 'Tablet', 'packet', 'amoxicillin+clavulanate', 'Antibiotics & Antifungals', false, true, false, 25.0, 50.0, 'Strip of 10', 10),
('Azithromycin', 'Zithromax', '500mg', 'Tablet', 'tablet', 'azithromycin', 'Antibiotics & Antifungals', false, true, false, 25.0, 55.0, 'Strip of 3', 3),
('Azithromycin neonatal drops', NULL, NULL, 'Drops', 'bottle', 'azithromycin neonatal', 'Antibiotics & Antifungals', false, false, true, 70.0, 150.0, 'Bottle 10ml', 1),
('Cefixime', NULL, '100mg', 'Tablet', 'bottle', 'cefixime', 'Antibiotics & Antifungals', false, true, false, 15.0, 35.0, 'Strip of 10', 10),
('Cefuroxime', 'Zinnat', '500mg', 'Tablet', 'bottle', 'cefuroxime', 'Antibiotics & Antifungals', false, true, false, 35.0, 70.0, 'Strip of 10', 10),
('Cefuroxime susp 125/5', 'Zinnat', '250mg', 'Syrup', 'bottle', 'cefuroxime 1255', 'Antibiotics & Antifungals', false, true, false, 35.0, 70.0, 'Strip of 10', 10),
('Cephalexin', NULL, '500mg', 'Capsule', 'tablet', 'cephalexin', 'Antibiotics & Antifungals', false, true, false, 6.0, 14.0, 'Strip of 10', 10),
('Cephalexin syrup 100mls', NULL, '100mg', 'Syrup', 'bottle', 'cephalexin', 'Antibiotics & Antifungals', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Ciprofloxacin', 'Cipro', '500mg', 'Tablet', 'tablet', 'ciprofloxacin', 'Antibiotics & Antifungals', false, true, false, 4.0, 10.0, 'Strip of 10', 10),
('Doxycycline', NULL, '100mg', 'Capsule', 'capsule', 'doxycycline', 'Antibiotics & Antifungals', false, true, false, 2.0, 5.0, 'Strip of 10', 10),
('Erythromycin', NULL, '250mg', 'Tablet', 'tablet', 'erythromycin', 'Antibiotics & Antifungals', false, true, false, 3.0, 8.0, 'Strip of 10', 10),
('Erythromycin', NULL, '500mg', 'Tablet', 'tablet', 'erythromycin', 'Antibiotics & Antifungals', false, true, false, 3.0, 8.0, 'Strip of 10', 10),
('Erythromycin susp 100mls', NULL, '250mg', 'Syrup', 'bottle', 'erythromycin', 'Antibiotics & Antifungals', false, true, false, 3.0, 8.0, 'Strip of 10', 10),
('Erythromycin susp 60mls', NULL, '250mg', 'Syrup', 'bottle', 'erythromycin', 'Antibiotics & Antifungals', false, true, false, 3.0, 8.0, 'Strip of 10', 10),
('Flamox', NULL, NULL, NULL, 'packet', 'flamox', 'Antibiotics & Antifungals', false, true, false, NULL, NULL, NULL, 1),
('Flucloxacillin', NULL, '250mg', 'Capsule', 'capsule', 'flucloxacillin', 'Antibiotics & Antifungals', false, true, false, 4.0, 10.0, 'Strip of 10', 10),
('Flucloxacillin', NULL, '500mg', 'Capsule', 'capsule', 'flucloxacillin', 'Antibiotics & Antifungals', false, true, false, 4.0, 10.0, 'Strip of 10', 10),
('Flucloxacillin suspension', 'Gaviscon', NULL, 'Syrup', 'bottle', 'flucloxacillin', 'Antibiotics & Antifungals', false, false, true, 220.0, 420.0, 'Bottle 200ml', 1),
('Fluconazole susp', 'Diflucan', '150mg', 'Syrup', 'bottle', 'fluconazole', 'Antibiotics & Antifungals', false, false, true, 25.0, 60.0, 'Single capsule', 1),
('Fluconazole', 'Diflucan', '200mg', 'Capsule', 'tablet', 'fluconazole', 'Antibiotics & Antifungals', false, false, true, 25.0, 60.0, 'Single capsule', 1),
('Griseofulvin', NULL, '125mg', 'Tablet', 'tablet', 'griseofulvin', 'Antibiotics & Antifungals', false, true, false, 6.0, 14.0, 'Strip of 10', 10),
('Griseofulvin', NULL, '250mg', 'Tablet', 'tablet', 'griseofulvin', 'Antibiotics & Antifungals', false, true, false, 6.0, 14.0, 'Strip of 10', 10),
('Griseofulvin', NULL, '500mg', 'Tablet', 'tablet', 'griseofulvin', 'Antibiotics & Antifungals', false, true, false, 6.0, 14.0, 'Strip of 10', 10),
('Helicoban', NULL, NULL, NULL, 'packet', 'helicoban', 'Antibiotics & Antifungals', false, true, false, NULL, NULL, NULL, 1),
('Hellicure kit', NULL, NULL, 'Kit', 'packet', 'hellicure kit', 'Antibiotics & Antifungals', false, false, true, 25.0, 70.0, 'Each', 1),
('Ketoconazole', 'Nizoral', '100mg', 'Tablet', 'tablet', 'ketoconazole', 'Antibiotics & Antifungals', false, true, false, 8.0, 18.0, 'Strip of 10', 10),
('Kitpylori kit', NULL, NULL, 'Kit', 'packet', 'kitpylori kit', 'Antibiotics & Antifungals', false, false, true, 25.0, 70.0, 'Each', 1),
('Levofloxacin', NULL, '500mg', 'Tablet', 'bottle', 'levofloxacin', 'Antibiotics & Antifungals', false, true, false, 18.0, 40.0, 'Strip of 5', 5),
('Levofloxacin', NULL, '750mg', 'Tablet', 'tablet', 'levofloxacin', 'Antibiotics & Antifungals', false, true, false, 18.0, 40.0, 'Strip of 5', 5),
('Nitrofurantoin', NULL, '100mg', 'Tablet', 'tablet', 'nitrofurantoin', 'Antibiotics & Antifungals', false, true, false, 5.0, 12.0, 'Strip of 10', 10),
('Norfloxacin', NULL, '400mg', 'Tablet', 'tablet', 'norfloxacin', 'Antibiotics & Antifungals', false, true, false, 5.0, 12.0, 'Strip of 10', 10),
('Nystatin 12', NULL, NULL, 'Syrup', 'bottle', 'nystatin 12', 'Antibiotics & Antifungals', false, true, false, NULL, NULL, NULL, 1),
('Nystatin 30mls', NULL, NULL, 'Syrup', 'bottle', 'nystatin', 'Antibiotics & Antifungals', false, true, false, NULL, NULL, NULL, 1),
('Ofhox/ornidazole', NULL, NULL, 'Tablet', 'tablet', 'ofhoxornidazole', 'Antibiotics & Antifungals', false, true, false, NULL, NULL, NULL, 1),
('Terbinafine', 'Lamisil', '250mg', 'Cream', 'tablet', 'terbinafine', 'Antibiotics & Antifungals', false, false, true, 220.0, 420.0, 'Tube 15g', 1),
('ABZ susp', NULL, NULL, 'Syrup', 'bottle', 'albendazole', 'Antiparasitics', false, false, true, NULL, NULL, NULL, 1),
('ABZ tabs', NULL, NULL, 'Tablet', 'tablet', 'albendazole', 'Antiparasitics', false, false, true, NULL, NULL, NULL, 1),
('Albaxate susp', NULL, NULL, 'Syrup', 'bottle', 'albendazole', 'Antiparasitics', false, false, true, NULL, NULL, NULL, 1),
('Levamisole susp', NULL, NULL, 'Syrup', 'bottle', 'levamisole', 'Antiparasitics', false, false, true, NULL, NULL, NULL, 1),
('Levamisole tabs', NULL, NULL, 'Tablet', 'tablet', 'levamisole', 'Antiparasitics', false, false, true, NULL, NULL, NULL, 1),
('Mebendazole susp', 'Vermox', '100mg', 'Syrup', 'bottle', 'mebendazole', 'Antiparasitics', false, false, true, 5.0, 12.0, 'Strip of 6', 6),
('Nilworm susp', NULL, NULL, 'Syrup', 'bottle', 'levamisole', 'Antiparasitics', false, false, true, NULL, NULL, NULL, 1),
('Nilworm tabs', NULL, NULL, 'Tablet', 'tablet', 'levamisole', 'Antiparasitics', false, false, true, NULL, NULL, NULL, 1),
('Olworm susp', NULL, NULL, 'Syrup', 'bottle', 'albendazole', 'Antiparasitics', false, false, true, NULL, NULL, NULL, 1),
('Olworm tabs', NULL, NULL, 'Tablet', 'tablet', 'albendazole', 'Antiparasitics', false, false, true, NULL, NULL, NULL, 1),
('Zentel susp', 'Zentel', '400mg', 'Syrup', 'bottle', 'zentel', 'Antiparasitics', false, false, true, 8.0, 20.0, 'Single tablet', 1),
('Zentel tabs', 'Zentel', '400mg', 'Tablet', 'tablet', 'zentel', 'Antiparasitics', false, false, true, 8.0, 20.0, 'Single tablet', 1),
('Amlodipine', NULL, '10mg', 'Tablet', 'tablet', 'amlodipine', 'Cardiovascular & Metabolic', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Amlodipine', NULL, '5mg', 'Tablet', 'tablet', 'amlodipine', 'Cardiovascular & Metabolic', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Artovastatin', NULL, '10mg', 'Tablet', 'tablet', 'artovastatin', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Artovastatin', NULL, '20mg', 'Tablet', 'tablet', 'artovastatin', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Ascard', NULL, '75mg', 'Tablet', 'tablet', 'aspirin', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Atenolol', NULL, '50mg', 'Tablet', 'tablet', 'atenolol', 'Cardiovascular & Metabolic', false, true, false, 2.0, 5.0, 'Strip of 10', 10),
('Calcicard', NULL, '20mg', 'Tablet', 'tablet', 'amlodipine', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Carbimazole', 'Neo-Mercazole', '5mg', 'Tablet', 'tablet', 'carbimazole', 'Cardiovascular & Metabolic', false, true, false, 4.0, 10.0, 'Strip of 10', 10),
('Cardisprin', NULL, '75mg', 'Tablet', 'tablet', 'aspirin', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Carditan', NULL, '50mg', 'Tablet', 'tablet', 'losartan', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Carditan H', NULL, NULL, 'Tablet', 'tablet', 'losartan', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Carvedilol', NULL, '12.5mg', 'Tablet', 'tablet', 'carvedilol', 'Cardiovascular & Metabolic', false, true, false, 5.0, 12.0, 'Strip of 10', 10),
('Carvedilol', NULL, '6.25mg', 'Tablet', 'tablet', 'carvedilol', 'Cardiovascular & Metabolic', false, true, false, 5.0, 12.0, 'Strip of 10', 10),
('Digoxin', NULL, '250mcg', 'Tablet', 'tablet', 'digoxin', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Enalapril', NULL, '5mg', 'Tablet', 'tablet', 'enalapril', 'Cardiovascular & Metabolic', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Enaril', NULL, '5mg', 'Tablet', 'tablet', 'enalapril', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Euthyrox', NULL, '100mcg', 'Tablet', 'tablet', 'levothyroxine', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Euthyrox', NULL, '50mcg', 'Tablet', 'tablet', 'levothyroxine', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Furosemide', 'Lasix', '40mg', 'Tablet', 'tablet', 'furosemide', 'Cardiovascular & Metabolic', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Glibenclamide', 'Daonil', '5mg', 'Tablet', 'tablet', 'glibenclamide', 'Cardiovascular & Metabolic', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Glucomet', NULL, '500mg', 'Tablet', 'tablet', 'metformin', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Glucomet', NULL, '850mg', 'Tablet', 'tablet', 'metformin', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Glucophage', 'Glucophage', '500mg', 'Tablet', 'tablet', 'glucophage', 'Cardiovascular & Metabolic', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Glucophage', 'Glucophage', '850mg', 'Tablet', 'tablet', 'glucophage', 'Cardiovascular & Metabolic', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('HCTZ', NULL, '25mg', 'Tablet', 'tablet', 'hctz', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('HCTZ', NULL, '50mg', 'Tablet', 'tablet', 'hctz', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Hydralazine', NULL, '25mg', 'Tablet', 'tablet', 'hydralazine', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Losartas', NULL, '50mg', 'Tablet', 'tablet', 'losartan', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Losartas HT', NULL, NULL, 'Tablet', 'tablet', 'losartan', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Metformin', 'Glucophage', '500mg', 'Tablet', 'tablet', 'metformin', 'Cardiovascular & Metabolic', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Methydopa', NULL, '250mg', 'Tablet', 'tablet', 'methydopa', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Nifedipine', NULL, '20mg', 'Tablet', 'tablet', 'nifedipine', 'Cardiovascular & Metabolic', false, true, false, 2.0, 5.0, 'Strip of 10', 10),
('Nogluc', NULL, '5mg', 'Tablet', 'tablet', 'glimepiride', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Presartan H', NULL, '50mg', 'Tablet', 'tablet', 'losartan', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Propranolol', NULL, '40mg', 'Tablet', 'tablet', 'propranolol', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Rivaroxaban', NULL, '10mg', 'Tablet', 'tablet', 'rivaroxaban', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Rivaroxaban', NULL, '15mg', 'Tablet', 'tablet', 'rivaroxaban', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Sinemet', NULL, '275mg', 'Tablet', 'tablet', 'levodopa+carbidopa', 'Cardiovascular & Metabolic', false, true, false, NULL, NULL, NULL, 1),
('Spironolactone', 'Aldactone', '25mg', 'Tablet', 'tablet', 'spironolactone', 'Cardiovascular & Metabolic', false, true, false, 3.0, 8.0, 'Strip of 10', 10),
('Tranexamic acid', 'Ponstan', '500mg', 'Tablet', 'tablet', 'tranexamic acid', 'Cardiovascular & Metabolic', false, false, true, 3.0, 8.0, 'Strip of 10', 10),
('Warfarin', NULL, '5mg', 'Tablet', 'tablet', 'warfarin', 'Cardiovascular & Metabolic', false, true, false, 3.0, 8.0, 'Strip of 10', 10),
('Bromocriptin', NULL, NULL, 'Capsule', 'capsule', 'bromocriptin', 'Contraceptives', false, false, true, NULL, NULL, NULL, 1),
('Choice 72', NULL, NULL, NULL, 'packet', 'choice 72', 'Contraceptives', false, false, true, NULL, NULL, NULL, 1),
('DEPO Injection', 'Depo-Provera', '150mg', 'Injection', 'vial', 'depo', 'Contraceptives', false, false, true, 120.0, 300.0, 'Vial', 1),
('Femipian', NULL, NULL, 'Tablet', 'tablet', 'femipian', 'Contraceptives', false, false, true, NULL, NULL, NULL, 1),
('Microgynon', 'Microgynon', NULL, 'Tablet', 'tablet', 'microgynon', 'Contraceptives', false, false, true, 40.0, 100.0, 'Cycle of 28', 1),
('Norethisterone', NULL, NULL, 'Tablet', 'tablet', 'norethisterone', 'Contraceptives', false, false, true, NULL, NULL, NULL, 1),
('Posthor', NULL, NULL, 'Injection', 'vial', 'posthor', 'Contraceptives', false, false, true, NULL, NULL, NULL, 1),
('Ambroxol syrup', NULL, '100mg', 'Syrup', 'bottle', 'ambroxol', 'Cough & Cold', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Ascoril expec 100ml', NULL, NULL, 'Syrup', 'bottle', 'expectorant', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Babymol susp', NULL, NULL, 'Syrup', 'bottle', 'babymol', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Benacoff expectorant', NULL, NULL, 'Syrup', 'bottle', 'benacoff', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Bromseal expectorant', NULL, NULL, 'Syrup', 'bottle', 'bromseal', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Brozedex expectorant', NULL, NULL, 'Syrup', 'bottle', 'brozedex', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Brustan 100mls', NULL, NULL, 'Syrup', 'bottle', 'ibuprofen+paracetamol', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Cadiphen expectorant', NULL, NULL, 'Syrup', 'bottle', 'cadiphen', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Cadistin expectorant', NULL, NULL, 'Syrup', 'bottle', 'cadistin', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Calpol 100mls', NULL, NULL, 'Syrup', 'bottle', 'paracetamol', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Calpol 60mls', NULL, NULL, 'Syrup', 'bottle', 'paracetamol', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Celestamine', NULL, NULL, 'Tablet', 'tablet', 'betamethasone+loratadine', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Certirine syrup', NULL, '100mg', 'Syrup', 'bottle', 'certirine', 'Cough & Cold', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Cetrizine', NULL, '10mg', 'Tablet', 'tablet', 'cetrizine', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Chestcoff syrup', NULL, '100mg', 'Syrup', 'bottle', 'chestcoff', 'Cough & Cold', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Cofta tabs', NULL, NULL, 'Tablet', 'tablet', 'cofta', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Cold flu caps', 'Coldcap', NULL, 'Capsule', 'capsule', 'cold flu', 'Cough & Cold', false, false, true, 5.0, 12.0, 'Strip of 10', 10),
('Coldcap original', 'Coldcap', NULL, 'Tablet', 'capsule', 'coldcap original', 'Cough & Cold', false, false, true, 5.0, 12.0, 'Strip of 10', 10),
('Coldcap syrup', NULL, '100mg', 'Syrup', 'bottle', 'coldcap', 'Cough & Cold', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Cpm susp 60mls', NULL, NULL, 'Syrup', 'bottle', 'chlorpheniramine', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Dacof syrup', NULL, '100mg', 'Syrup', 'bottle', 'dacof', 'Cough & Cold', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Dacold caps', NULL, NULL, 'Capsule', 'capsule', 'dacold', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Daleased expectorant', NULL, NULL, 'Syrup', 'bottle', 'daleased', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Desloratadine', NULL, NULL, 'Tablet', 'tablet', 'desloratadine', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Dr toux', NULL, NULL, 'Syrup', 'bottle', 'dr toux', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Flucodex', NULL, NULL, 'Capsule', 'capsule', 'flucodex', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Flugone caps', NULL, NULL, 'Capsule', 'capsule', 'flugone', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Fricks lozenges', 'Strepsils', NULL, 'Lozenge', 'lozenge', 'fricks', 'Cough & Cold', false, false, true, 4.0, 10.0, 'Pack of 8', 8),
('Glycoff syrup', NULL, '100mg', 'Syrup', 'bottle', 'glycoff', 'Cough & Cold', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Good morning syrup', NULL, '100mg', 'Syrup', 'bottle', 'good morning', 'Cough & Cold', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Ibugesic 100mls', NULL, NULL, 'Syrup', 'bottle', 'ibuprofen', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Ibugesic 60mls', NULL, NULL, 'Syrup', 'bottle', 'ibuprofen', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Ibuprofen syrup 100mls', NULL, '100mg', 'Syrup', 'bottle', 'ibuprofen', 'Cough & Cold', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Ibuprofen syrup 60mls', NULL, '100mg', 'Syrup', 'bottle', 'ibuprofen', 'Cough & Cold', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Levocetirizine', NULL, '5mg', 'Tablet', 'tablet', 'levocetirizine', 'Cough & Cold', false, false, true, 3.0, 8.0, 'Strip of 10', 10),
('Loratadine', NULL, '10mg', 'Tablet', 'tablet', 'loratadine', 'Cough & Cold', false, false, true, 2.5, 6.0, 'Strip of 10', 10),
('Meftan plus', NULL, NULL, 'Tablet', 'tablet', 'meftan', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Panadol baby 100mls', 'Panadol', '500mg', 'Tablet', 'bottle', 'paracetamol', 'Cough & Cold', false, false, true, 1.2, 3.0, 'Strip of 10', 10),
('Panadol baby 60mls', 'Panadol', '500mg', 'Tablet', 'bottle', 'paracetamol', 'Cough & Cold', false, false, true, 1.2, 3.0, 'Strip of 10', 10),
('Paracetamol susp 60mls', 'Panadol', '500mg', 'Syrup', 'bottle', 'paracetamol', 'Cough & Cold', false, false, true, 1.2, 3.0, 'Strip of 10', 10),
('Piriton syrup', NULL, '100mg', 'Syrup', 'bottle', 'chlorpheniramine', 'Cough & Cold', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Pirton tabs', NULL, '2mg', 'Tablet', 'tablet', 'chlorpheniramine', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Stepsils', NULL, NULL, 'Lozenge', 'lozenge', 'lozenge', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Stugeron tabs', 'Stugeron', '25mg', 'Tablet', 'tablet', 'stugeron', 'Cough & Cold', false, false, true, 3.0, 8.0, 'Strip of 10', 10),
('Surdex 120ml', NULL, NULL, 'Syrup', 'bottle', 'surdex', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Tricoff 100mls', NULL, NULL, 'Syrup', 'bottle', 'tricoff', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Tricoff 60mls', NULL, NULL, 'Syrup', 'bottle', 'tricoff', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Tricohist 100mls', NULL, NULL, 'Syrup', 'bottle', 'tricohist', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Tricohist 60mls', NULL, NULL, 'Syrup', 'bottle', 'tricohist', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Tridex 100mls', NULL, NULL, 'Syrup', 'bottle', 'tridex', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Tridex 60mls', NULL, NULL, 'Syrup', 'bottle', 'tridex', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Tuspel 60mls', NULL, NULL, 'Syrup', 'bottle', 'tuspel', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Tuspel plus 100mls', NULL, NULL, 'Syrup', 'bottle', 'tuspel', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Upacoff expectorant', NULL, NULL, 'Syrup', 'bottle', 'upacoff', 'Cough & Cold', false, false, true, NULL, NULL, NULL, 1),
('Zefcolin syrup', NULL, '100mg', 'Syrup', 'bottle', 'zefcolin', 'Cough & Cold', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Acyclovir eye ointment', NULL, NULL, 'Ointment', 'tube', 'acyclovir eye', 'Eye & Ear Drops', false, false, true, 70.0, 150.0, 'Bottle 10ml', 1),
('Azelastine eyedrops', NULL, NULL, 'Drops', 'bottle', 'azelastine eyedrops', 'Eye & Ear Drops', false, false, true, NULL, NULL, NULL, 1),
('Cipro-dex eyedrops', 'Cipro', '500mg', 'Drops', 'bottle', 'cipro-dex eyedrops', 'Eye & Ear Drops', false, true, false, 4.0, 10.0, 'Strip of 10', 10),
('Dexomet N', NULL, NULL, 'Syrup', 'bottle', 'dexomet n', 'Eye & Ear Drops', false, false, true, NULL, NULL, NULL, 1),
('Gentamycin eye drops', NULL, NULL, 'Drops', 'bottle', 'gentamycin eye', 'Eye & Ear Drops', false, false, true, 70.0, 150.0, 'Bottle 10ml', 1),
('Hydrocortisone eye drops', NULL, NULL, 'Drops', 'bottle', 'hydrocortisone eye', 'Eye & Ear Drops', false, false, true, 70.0, 150.0, 'Bottle 10ml', 1),
('Hypromellose eye drops', NULL, NULL, 'Drops', 'bottle', 'hypromellose eye', 'Eye & Ear Drops', false, false, true, 70.0, 150.0, 'Bottle 10ml', 1),
('Hystalyn eyedrops', NULL, NULL, 'Drops', 'bottle', 'hystalyn eyedrops', 'Eye & Ear Drops', false, false, true, NULL, NULL, NULL, 1),
('Isoryn adult', NULL, NULL, 'Syrup', 'bottle', 'isoryn', 'Eye & Ear Drops', false, false, true, NULL, NULL, NULL, 1),
('Isoryn paed', NULL, NULL, 'Syrup', 'bottle', 'isoryn', 'Eye & Ear Drops', false, false, true, NULL, NULL, NULL, 1),
('Ketorolac eyedrops', NULL, NULL, 'Drops', 'bottle', 'ketorolac eyedrops', 'Eye & Ear Drops', false, false, true, NULL, NULL, NULL, 1),
('Maxitrol eye ointment', NULL, NULL, 'Ointment', 'bottle', 'dexamethasone+neomycin', 'Eye & Ear Drops', false, false, true, 70.0, 150.0, 'Bottle 10ml', 1),
('Maxitrol eyedrops', NULL, NULL, 'Drops', 'bottle', 'dexamethasone+neomycin', 'Eye & Ear Drops', false, false, true, NULL, NULL, NULL, 1),
('Nasal drops', NULL, NULL, 'Drops', 'bottle', 'nasal', 'Eye & Ear Drops', false, false, true, 70.0, 150.0, 'Bottle 10ml', 1),
('Olapatadine eyedrops', NULL, NULL, 'Drops', 'bottle', 'olapatadine eyedrops', 'Eye & Ear Drops', false, false, true, NULL, NULL, NULL, 1),
('Otorex ear drops', NULL, NULL, 'Drops', 'bottle', 'otorex ear', 'Eye & Ear Drops', false, false, true, 70.0, 150.0, 'Bottle 10ml', 1),
('Prednisolone eye drops', NULL, NULL, 'Drops', 'bottle', 'prednisolone eye', 'Eye & Ear Drops', false, false, true, 70.0, 150.0, 'Bottle 10ml', 1),
('Probeta eyedrops', NULL, NULL, 'Drops', 'bottle', 'probeta eyedrops', 'Eye & Ear Drops', false, false, true, NULL, NULL, NULL, 1),
('TEO', NULL, NULL, 'Cream', 'tube', 'teo', 'Eye & Ear Drops', false, false, true, NULL, NULL, NULL, 1),
('Tears naturale', NULL, NULL, 'Syrup', 'bottle', 'tears naturale', 'Eye & Ear Drops', false, false, true, NULL, NULL, NULL, 1),
('Timolol eyedrops', NULL, NULL, 'Drops', 'bottle', 'timolol eyedrops', 'Eye & Ear Drops', false, false, true, NULL, NULL, NULL, 1),
('Acyclovir', NULL, '400mg', 'Tablet', 'tablet', 'acyclovir', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Amikacin inj', NULL, NULL, 'Injection', 'vial', 'amikacin', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Aminosidine', NULL, '250mg', 'Tablet', 'tablet', 'aminosidine', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Aminosidine syrup 60mls', NULL, '100mg', 'Syrup', 'bottle', 'aminosidine', 'Injections & Misc', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Antirables', NULL, NULL, 'Injection', 'vial', 'antirables', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Artesunate inj', NULL, '60mg', 'Injection', 'vial', 'artesunate', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Benzathine', 'Postinor-2', '2.4MU', 'Tablet', 'ampoule', 'benzathine', 'Injections & Misc', false, false, true, 90.0, 200.0, 'Pack of 2', 1),
('Benzylpenicillin', NULL, '5MU', 'Injection', 'ampoule', 'benzylpenicillin', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('CTX 100mls', NULL, NULL, 'Syrup', 'bottle', 'co-trimoxazole', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('CTX', NULL, '480mg', 'Tablet', 'tablet', 'co-trimoxazole', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('CTX 60mls', NULL, NULL, 'Syrup', 'bottle', 'co-trimoxazole', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('CTX', NULL, '960mg', 'Tablet', 'tablet', 'co-trimoxazole', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Ceftriaxone inj', NULL, '1g', 'Injection', 'vial', 'ceftriaxone', 'Injections & Misc', false, true, false, 80.0, 180.0, 'Vial', 1),
('Clarithromycin', 'Klaricid', '500mg', 'Tablet', 'tablet', 'clarithromycin', 'Injections & Misc', false, true, false, 35.0, 70.0, 'Strip of 10', 10),
('Clindamycin', 'Dalacin C', '150mg', 'Capsule', 'capsule', 'clindamycin', 'Injections & Misc', false, true, false, 20.0, 45.0, 'Strip of 10', 10),
('Clindamycin', 'Dalacin C', '300mg', 'Capsule', 'capsule', 'clindamycin', 'Injections & Misc', false, true, false, 20.0, 45.0, 'Strip of 10', 10),
('Clotrimazole pess', 'Canesten', '100mg', 'Pessary', 'packet', 'clotrimazole', 'Injections & Misc', false, false, true, 90.0, 180.0, 'Tube 20g', 1),
('Clotrimazole pess', 'Canesten', '200mg', 'Pessary', 'packet', 'clotrimazole', 'Injections & Misc', false, false, true, 90.0, 180.0, 'Tube 20g', 1),
('Clotrimazole pess', 'Canesten', '500mg', 'Pessary', 'packet', 'clotrimazole', 'Injections & Misc', false, false, true, 90.0, 180.0, 'Tube 20g', 1),
('Daflon', NULL, '500mg', 'Tablet', 'tablet', 'diosmin+hesperidin', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Dextrose 5%', NULL, NULL, 'Syrup', 'bottle', 'dextrose 5', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Diclofenac inj', 'Voltaren', NULL, 'Injection', 'vial', 'diclofenac', 'Injections & Misc', false, false, true, 180.0, 350.0, 'Tube 20g', 1),
('Diracip M tabs', NULL, NULL, 'Tablet', 'tablet', 'antacid', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Enterozole tabs', NULL, NULL, 'Tablet', 'tablet', 'metronidazole+furazolidone', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Esgyno Kit', NULL, NULL, 'Kit', 'piece', 'esgyno kit', 'Injections & Misc', false, false, true, 25.0, 70.0, 'Each', 1),
('Fanlar', NULL, NULL, 'Tablet', 'tablet', 'sulfadoxine+pyrimethamine', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Flucloxacillin inj', NULL, '500mg', 'Injection', 'vial', 'flucloxacillin', 'Injections & Misc', false, true, false, 4.0, 10.0, 'Strip of 10', 10),
('Fluphenazine inj', NULL, NULL, 'Injection', 'ampoule', 'fluphenazine', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Gentamycin inj', NULL, '80mg', 'Injection', 'vial', 'gentamycin', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Hydrocortisone inj', NULL, NULL, 'Injection', 'vial', 'hydrocortisone', 'Injections & Misc', false, false, true, 70.0, 150.0, 'Tube 15g', 1),
('Ketesse inj', NULL, NULL, 'Injection', 'ampoule', 'ketesse', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Kridofos inj', NULL, NULL, 'Injection', 'vial', 'kridofos', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Lignocaine inj', NULL, NULL, 'Injection', 'vial', 'lignocaine', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Lonart', NULL, NULL, 'Tablet', 'tablet', 'artemether+lumefantrine', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Mixtard', 'Mixtard', '100iu', 'Injection', 'vial', 'mixtard', 'Injections & Misc', false, true, false, 450.0, 750.0, 'Vial 10ml', 1),
('Neurotrol (carbamazepine) tabs', 'Tegretol', '200mg', 'Tablet', 'tablet', 'neurotrol carbamazepine', 'Injections & Misc', false, true, false, 3.0, 8.0, 'Strip of 10', 10),
('Normal saline', NULL, NULL, 'Solution', 'bottle', 'normal saline', 'Injections & Misc', false, false, true, 80.0, 160.0, 'Bottle 500ml', 1),
('Omeprazole inj', NULL, '20mg', 'Injection', 'vial', 'omeprazole', 'Injections & Misc', false, false, true, 2.0, 6.0, 'Strip of 10', 10),
('Plasil inj', 'Plasil', '10mg', 'Injection', 'ampoule', 'metoclopramide', 'Injections & Misc', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Ringers lactate', NULL, NULL, 'Syrup', 'bottle', 'ringers lactate', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('SP tabs', NULL, NULL, 'Tablet', 'tablet', 'sp', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Sildenafil', NULL, '100mg', 'Tablet', 'tablet', 'sildenafil', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Sildenafil', NULL, '50mg', 'Tablet', 'tablet', 'sildenafil', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Tamsulosin', NULL, '0.4mg', 'Capsule', 'capsule', 'tamsulosin', 'Injections & Misc', false, true, false, NULL, NULL, NULL, 1),
('Tramadol inj', NULL, '50mg', 'Injection', 'ampoule', 'tramadol', 'Injections & Misc', true, true, false, 4.0, 10.0, 'Strip of 10', 10),
('Tranexamic acid inj', 'Ponstan', '500mg', 'Injection', 'ampoule', 'tranexamic acid', 'Injections & Misc', false, false, true, 3.0, 8.0, 'Strip of 10', 10),
('Vitamin B complex inj', NULL, NULL, 'Injection', 'vial', 'vitamin b complex', 'Injections & Misc', false, false, true, 1.5, 4.0, 'Strip of 10', 10),
('Action', NULL, NULL, NULL, 'pair', 'action', 'Misc', false, false, true, NULL, NULL, NULL, 1),
('Caustic pencil', NULL, NULL, NULL, 'piece', 'caustic pencil', 'Misc', false, false, true, NULL, NULL, NULL, 1),
('Mara moja', NULL, NULL, NULL, 'pair', 'mara moja', 'Misc', false, false, true, NULL, NULL, NULL, 1),
('Sonamoja', NULL, NULL, NULL, 'pair', 'sonamoja', 'Misc', false, false, true, NULL, NULL, NULL, 1),
('Tumbocid', NULL, NULL, NULL, 'pair', 'tumbocid', 'Misc', false, false, true, NULL, NULL, NULL, 1),
('Acedofenac', NULL, '100mg', 'Tablet', 'tablet', 'aceclofenac', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Acepar', NULL, NULL, 'Tablet', 'tablet', 'aceclofenac+paracetamol', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Acepar MR', NULL, NULL, 'Tablet', 'tablet', 'aceclofenac+paracetamol', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Brustan tabs', NULL, NULL, 'Tablet', 'tablet', 'ibuprofen+paracetamol', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Celecoxib', NULL, '100mg', 'Tablet', 'tablet', 'celecoxib', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Celecoxib', NULL, '200mg', 'Tablet', 'tablet', 'celecoxib', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Dexamethasone tabs', NULL, '4mg', 'Tablet', 'tablet', 'dexamethasone', 'Pain & Anti-inflammatory', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Diclofenac', 'Voltaren', '100mg', 'Gel', 'tablet', 'diclofenac', 'Pain & Anti-inflammatory', false, false, true, 180.0, 350.0, 'Tube 20g', 1),
('Diclofenac', 'Voltaren', '50mg', 'Gel', 'tablet', 'diclofenac', 'Pain & Anti-inflammatory', false, false, true, 180.0, 350.0, 'Tube 20g', 1),
('Diclomal SR', NULL, NULL, 'Tablet', 'tablet', 'diclofenac', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Doloact', NULL, NULL, 'Tablet', 'tablet', 'doloact', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Eterocoxib', NULL, '120mg', 'Tablet', 'tablet', 'eterocoxib', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Eterocoxib', NULL, '90mg', 'Tablet', 'tablet', 'eterocoxib', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Flamoryl s', NULL, NULL, 'Tablet', 'tablet', 'flamoryl s', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Hedex', NULL, NULL, NULL, 'packet', 'paracetamol', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Ibuprofen', 'Brufen', '200mg', 'Tablet', 'tablet', 'ibuprofen', 'Pain & Anti-inflammatory', false, false, true, 1.5, 4.0, 'Strip of 10', 10),
('Ibuprofen', 'Brufen', '400mg', 'Tablet', 'tablet', 'ibuprofen', 'Pain & Anti-inflammatory', false, false, true, 1.5, 4.0, 'Strip of 10', 10),
('Indomethacin caps', NULL, NULL, 'Capsule', 'capsule', 'indomethacin', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Lobak', NULL, NULL, 'Tablet', 'tablet', 'lobak', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Mefenamic acid', 'Ponstan', '250mg', 'Tablet', 'tablet', 'mefenamic acid', 'Pain & Anti-inflammatory', false, false, true, 3.0, 8.0, 'Strip of 10', 10),
('Mefenamic acid', 'Ponstan', '500mg', 'Tablet', 'tablet', 'mefenamic acid', 'Pain & Anti-inflammatory', false, false, true, 3.0, 8.0, 'Strip of 10', 10),
('Meloxicam', NULL, '15mg', 'Tablet', 'tablet', 'meloxicam', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Meloxicam', NULL, '7.5mg', 'Tablet', 'tablet', 'meloxicam', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Myospaz', NULL, NULL, 'Tablet', 'tablet', 'ibuprofen+chlorzoxazone', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Panadol Extra', 'Panadol Extra', '500mg', 'Tablet', 'tablet', 'paracetamol', 'Pain & Anti-inflammatory', false, false, true, 3.5, 7.0, 'Strip of 10', 10),
('Panadol advance', 'Panadol', '500mg', 'Tablet', 'tablet', 'paracetamol', 'Pain & Anti-inflammatory', false, false, true, 1.2, 3.0, 'Strip of 10', 10),
('Paracetamol', 'Panadol', '500mg', 'Tablet', 'tablet', 'paracetamol', 'Pain & Anti-inflammatory', false, false, true, 1.2, 3.0, 'Strip of 10', 10),
('Piroxicam caps', NULL, NULL, 'Capsule', 'capsule', 'piroxicam', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Prednisolone', NULL, '5mg', 'Tablet', 'tablet', 'prednisolone', 'Pain & Anti-inflammatory', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Rilit MR', NULL, NULL, 'Tablet', 'tablet', 'rilit', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Subsyde CR', NULL, NULL, 'Tablet', 'tablet', 'diclofenac', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Zulu', NULL, NULL, 'Tablet', 'tablet', 'aceclofenac', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Zulu MR', NULL, NULL, 'Tablet', 'tablet', 'aceclofenac', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Zulu SP', NULL, NULL, 'Tablet', 'tablet', 'aceclofenac', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Zyrtai MR', NULL, NULL, 'Tablet', 'tablet', 'cetirizine', 'Pain & Anti-inflammatory', false, false, true, NULL, NULL, NULL, 1),
('Amitriptyline', NULL, '25mg', 'Tablet', 'tablet', 'amitriptyline', 'Psychiatric Medications', true, true, false, 2.0, 5.0, 'Strip of 10', 10),
('Benzhexol', NULL, '5mg', 'Capsule', 'capsule', 'benzhexol', 'Psychiatric Medications', false, true, false, NULL, NULL, NULL, 1),
('Carbamazepine', 'Tegretol', '200mg', 'Tablet', 'tablet', 'carbamazepine', 'Psychiatric Medications', false, true, false, 3.0, 8.0, 'Strip of 10', 10),
('Chlorpromazine', NULL, '100mg', 'Tablet', 'tablet', 'chlorpromazine', 'Psychiatric Medications', true, true, false, NULL, NULL, NULL, 1),
('Fluoxetine', 'Prozac', '20mg', 'Capsule', 'tablet', 'fluoxetine', 'Psychiatric Medications', false, true, false, 5.0, 12.0, 'Strip of 10', 10),
('Gabapentin', 'Neurontin', '300mg', 'Capsule', 'tablet', 'gabapentin', 'Psychiatric Medications', false, true, false, 8.0, 18.0, 'Strip of 10', 10),
('Haloperidol', NULL, '5mg', 'Tablet', 'tablet', 'haloperidol', 'Psychiatric Medications', true, true, false, NULL, NULL, NULL, 1),
('Misoprostol', NULL, '200mcg', 'Tablet', 'tablet', 'misoprostol', 'Psychiatric Medications', false, true, false, NULL, NULL, NULL, 1),
('Olanzapine', NULL, '10mg', 'Capsule', 'capsule', 'olanzapine', 'Psychiatric Medications', false, true, false, NULL, NULL, NULL, 1),
('Phenobarbitone', NULL, '30mg', 'Tablet', 'tablet', 'phenobarbitone', 'Psychiatric Medications', true, true, false, NULL, NULL, NULL, 1),
('Phenytoin', NULL, '100mg', 'Tablet', 'tablet', 'phenytoin', 'Psychiatric Medications', false, true, false, NULL, NULL, NULL, 1),
('Pregabalin', 'Lyrica', '150mg', 'Capsule', 'tablet', 'pregabalin', 'Psychiatric Medications', true, true, false, 12.0, 25.0, 'Strip of 10', 10),
('Pregabalin', 'Lyrica', '75mg', 'Capsule', 'capsule', 'pregabalin', 'Psychiatric Medications', true, true, false, 12.0, 25.0, 'Strip of 10', 10),
('Tramadol', NULL, '50mg', 'Capsule', 'capsule', 'tramadol', 'Psychiatric Medications', true, true, false, 4.0, 10.0, 'Strip of 10', 10),
('Vitapyn tabs', NULL, NULL, 'Tablet', 'tablet', 'vitapyn', 'Psychiatric Medications', false, true, false, NULL, NULL, NULL, 1),
('Aerocort inhaler', 'Becotide', '250mcg', 'Inhaler', 'can', 'aerocort inhaler', 'Respiratory', false, true, false, 350.0, 650.0, 'Inhaler', 1),
('Aerovent inhaler', 'Becotide', '250mcg', 'Inhaler', 'can', 'aerovent inhaler', 'Respiratory', false, true, false, 350.0, 650.0, 'Inhaler', 1),
('Budecort inhaler', 'Becotide', '250mcg', 'Inhaler', 'can', 'budecort inhaler', 'Respiratory', false, true, false, 350.0, 650.0, 'Inhaler', 1),
('Foralin inhaler', 'Becotide', '250mcg', 'Inhaler', 'can', 'foralin inhaler', 'Respiratory', false, true, false, 350.0, 650.0, 'Inhaler', 1),
('Franol', NULL, NULL, 'Tablet', 'tablet', 'franol', 'Respiratory', false, false, true, NULL, NULL, NULL, 1),
('Montelukast', 'Singulair', '10mg', 'Tablet', 'tablet', 'montelukast', 'Respiratory', false, true, false, 12.0, 25.0, 'Strip of 10', 10),
('Montelukast chew', 'Singulair', '10mg', 'Tablet', 'tablet', 'montelukast chew', 'Respiratory', false, true, false, 12.0, 25.0, 'Strip of 10', 10),
('Salbutamol', 'Ventolin', '4mg', 'Tablet', 'tablet', 'salbutamol', 'Respiratory', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Salbutamol inhaler', 'Ventolin', '4mg', 'Inhaler', 'can', 'salbutamol inhaler', 'Respiratory', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Salbutamol susp 100ml', 'Ventolin', '4mg', 'Syrup', 'bottle', 'salbutamol', 'Respiratory', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Salbutamol susp 60ml', 'Ventolin', '4mg', 'Syrup', 'bottle', 'salbutamol', 'Respiratory', false, true, false, 1.5, 4.0, 'Strip of 10', 10),
('Ventolin inhaler', 'Becotide', '250mcg', 'Inhaler', 'can', 'ventolin inhaler', 'Respiratory', false, true, false, 350.0, 650.0, 'Inhaler', 1),
('Acnesol cream', 'Daktarin', NULL, 'Cream', 'tube', 'acnesol', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Acyclovir ointment', NULL, NULL, 'Ointment', 'tube', 'acyclovir', 'Topicals', false, false, true, 50.0, 110.0, 'Tube 25g', 1),
('Anomex suppositories', NULL, NULL, 'Suppository', 'piece', 'hemorrhoid', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Anusol suppositories', NULL, NULL, 'Suppository', 'piece', 'hemorrhoid', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Anustat ointment', NULL, NULL, 'Ointment', 'tube', 'anustat', 'Topicals', false, false, true, 50.0, 110.0, 'Tube 25g', 1),
('Axel oil chapa shoka', 'Seven Seas', NULL, 'Capsule', 'tube', 'axel oil chapa shoka', 'Topicals', false, false, true, 500.0, 900.0, 'Bottle of 60', 1),
('Beclomin ointment', NULL, NULL, 'Ointment', 'tube', 'beclomin', 'Topicals', false, false, true, 50.0, 110.0, 'Tube 25g', 1),
('Benzyl benzoate', NULL, NULL, 'Syrup', 'bottle', 'benzyl benzoate', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Betamed cream', 'Daktarin', NULL, 'Cream', 'tube', 'betamed', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Betason cream', 'Daktarin', NULL, 'Cream', 'tube', 'betason', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Bio-oil 60mls', 'Seven Seas', NULL, 'Capsule', 'bottle', 'bio-oil', 'Topicals', false, false, true, 500.0, 900.0, 'Bottle of 60', 1),
('Bulkot', NULL, NULL, 'Cream', 'tube', 'bulkot', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Bulkot b', NULL, NULL, 'Tablet', 'tube', 'bulkot b', 'Topicals', false, false, true, 1.5, 4.0, 'Strip of 10', 10),
('CHX gel', NULL, NULL, 'Gel', 'tube', 'chx', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Calamine lotion', NULL, NULL, 'Lotion', 'bottle', 'calamine', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Candid B cream', 'Daktarin', NULL, 'Cream', 'tube', 'clotrimazole', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Candid mouth paint', NULL, NULL, 'Solution', 'bottle', 'clotrimazole', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Candid powder', NULL, NULL, 'Powder', 'bottle', 'clotrimazole', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Clob B cream', 'Daktarin', NULL, 'Cream', 'tube', 'clob b', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Clotrimazole cream', 'Daktarin', NULL, 'Cream', 'tube', 'clotrimazole', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Clotrine b', NULL, NULL, 'Tablet', 'tube', 'clotrine b', 'Topicals', false, false, true, 1.5, 4.0, 'Strip of 10', 10),
('Clozole B cream', 'Daktarin', NULL, 'Cream', 'tube', 'clozole b', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Dazole mouth paint', NULL, NULL, 'Solution', 'bottle', 'dazole mouth paint', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Deep heat cream', 'Deep Heat', '15g', 'Cream', 'tube', 'deep heat', 'Topicals', false, false, true, 200.0, 380.0, 'Tube 35g', 1),
('Deep heat cream', 'Deep Heat', '35g', 'Cream', 'tube', 'deep heat', 'Topicals', false, false, true, 200.0, 380.0, 'Tube 35g', 1),
('Deep heat spray', 'Deep Heat', NULL, 'Spray', 'can', 'deep heat', 'Topicals', false, false, true, 200.0, 380.0, 'Tube 35g', 1),
('Deflam spray', NULL, NULL, 'Spray', 'can', 'deflam', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Diclofenac cream', 'Voltaren', NULL, 'Cream', 'tube', 'diclofenac', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 20g', 1),
('Elyvate cream', 'Daktarin', NULL, 'Cream', 'tube', 'elyvate', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Epiderm cream', 'Daktarin', NULL, 'Cream', 'tube', 'epiderm', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Exevate mf cream', 'Daktarin', NULL, 'Cream', 'tube', 'exevate mf', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Funbact cream', 'Daktarin', NULL, 'Cream', 'tube', 'clotrimazole', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Funbact powder', NULL, NULL, 'Powder', 'can', 'clotrimazole', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Futsil herbal', NULL, NULL, 'Syrup', 'bottle', 'futsil', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Grabacin powder', NULL, NULL, 'Powder', 'bottle', 'grabacin', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Hydrocortisone cream', 'Daktarin', NULL, 'Cream', 'tube', 'hydrocortisone', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Intamin cream', 'Daktarin', NULL, 'Cream', 'tube', 'intamin', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Kaluma pain balm', NULL, NULL, 'Balm', 'tube', 'kaluma pain', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Ketoconazole cream', 'Daktarin', NULL, 'Cream', 'tube', 'ketoconazole', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Ketoprofen cream', 'Daktarin', NULL, 'Cream', 'tube', 'ketoprofen', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Klv gel', NULL, NULL, 'Gel', 'tube', 'klv', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Lanolin cream', 'Daktarin', NULL, 'Cream', 'tube', 'lanolin', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Mediven S cream', 'Daktarin', NULL, 'Cream', 'tube', 'mediven s', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Mediven cream', 'Daktarin', NULL, 'Cream', 'tube', 'mediven', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Menthoplus', NULL, NULL, 'Cream', 'tube', 'menthoplus', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Miconazole cream', 'Daktarin', NULL, 'Cream', 'tube', 'miconazole', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Microenema 20mls', NULL, NULL, 'Cream', 'tube', 'microenema', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Mometasone oint', NULL, NULL, 'Ointment', 'tube', 'mometasone', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Mupiricin ointment', NULL, NULL, 'Ointment', 'tube', 'mupiricin', 'Topicals', false, false, true, 50.0, 110.0, 'Tube 25g', 1),
('Nauma pain balm', NULL, NULL, 'Balm', 'tube', 'nauma pain', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Nebanol', NULL, '10g', 'Syrup', 'bottle', 'nebanol', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Nebanol', NULL, '5g', 'Syrup', 'bottle', 'nebanol', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Norash', NULL, NULL, 'Cream', 'tube', 'norash', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Paracetamol supp', 'Panadol', '500mg', 'Tablet', 'piece', 'paracetamol supp', 'Topicals', false, false, true, 1.2, 3.0, 'Strip of 10', 10),
('Pernex AC', NULL, NULL, 'Cream', 'tube', 'pernex ac', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Pharmasal ointment', NULL, NULL, 'Ointment', 'tube', 'pharmasal', 'Topicals', false, false, true, 50.0, 110.0, 'Tube 25g', 1),
('Pharmasal spray', NULL, NULL, 'Spray', 'can', 'pharmasal', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('SSD cream', 'Daktarin', NULL, 'Cream', 'tube', 'ssd', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Sulphur ointment', NULL, NULL, 'Ointment', 'tube', 'sulphur', 'Topicals', false, false, true, 50.0, 110.0, 'Tube 25g', 1),
('Tacrolimus ointment', NULL, NULL, 'Ointment', 'tube', 'tacrolimus', 'Topicals', false, false, true, 50.0, 110.0, 'Tube 25g', 1),
('Terbinafine cream', 'Lamisil', NULL, 'Cream', 'tube', 'terbinafine', 'Topicals', false, false, true, 220.0, 420.0, 'Tube 15g', 1),
('Tetracycline skin ointment', NULL, NULL, 'Ointment', 'tube', 'tetracycline skin', 'Topicals', false, false, true, 50.0, 110.0, 'Tube 25g', 1),
('Volini gel', NULL, NULL, 'Gel', 'tube', 'diclofenac', 'Topicals', false, false, true, NULL, NULL, NULL, 1),
('Whitesfield ointment', NULL, NULL, 'Ointment', 'tube', 'whitesfield', 'Topicals', false, false, true, 50.0, 110.0, 'Tube 25g', 1),
('Xtraderm cream', 'Daktarin', NULL, 'Cream', 'tube', 'xtraderm', 'Topicals', false, false, true, 180.0, 350.0, 'Tube 30g', 1),
('Zupricin B ointment', NULL, NULL, 'Ointment', 'tube', 'zupricin b', 'Topicals', false, false, true, 1.5, 4.0, 'Strip of 10', 10),
('Zupricin ointment', NULL, NULL, 'Ointment', 'tube', 'zupricin', 'Topicals', false, false, true, 50.0, 110.0, 'Tube 25g', 1),
('Ascorbic acid', 'Ponstan', '500mg', 'Tablet', 'tablet', 'ascorbic acid', 'Vitamins & Supplements', false, false, true, 3.0, 8.0, 'Strip of 10', 10),
('Astymin', NULL, NULL, 'Syrup', 'bottle', 'amino acids', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Becoactin syrup 200ml', NULL, '100mg', 'Syrup', 'bottle', 'vitamin b complex', 'Vitamins & Supplements', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Becoactin tabs', NULL, NULL, 'Tablet', 'tablet', 'vitamin b complex', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Bonnisan', NULL, NULL, 'Syrup', 'bottle', 'bonnisan', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Byofer 12 syrup', NULL, '100mg', 'Syrup', 'bottle', 'byofer 12', 'Vitamins & Supplements', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Cartil forte', NULL, NULL, 'Capsule', 'capsule', 'cartil', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Cypro B plus 200mls', NULL, NULL, 'Tablet', 'bottle', 'cypro b', 'Vitamins & Supplements', false, false, true, 1.5, 4.0, 'Strip of 10', 10),
('Cypro B plus tabs', NULL, NULL, 'Tablet', 'tablet', 'cypro b', 'Vitamins & Supplements', false, false, true, 1.5, 4.0, 'Strip of 10', 10),
('Essneuroit', NULL, NULL, 'Tablet', 'tablet', 'essneuroit', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Ferrous sulphate', NULL, '200mg', 'Tablet', 'tablet', 'ferrous sulphate', 'Vitamins & Supplements', false, false, true, 1.0, 3.0, 'Strip of 10', 10),
('Floranorm', NULL, NULL, 'Sachet', 'sachet', 'floranorm', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Folic acid', NULL, '5mg', 'Tablet', 'tablet', 'folic acid', 'Vitamins & Supplements', false, false, true, 1.0, 3.0, 'Strip of 10', 10),
('Gypon 100mls', NULL, NULL, 'Syrup', 'bottle', 'gypon', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Hemovit', NULL, NULL, 'Syrup', 'bottle', 'hemovit', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Jointfix', NULL, NULL, 'Capsule', 'capsule', 'jointfix', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Multivitamin 100mls', NULL, NULL, 'Tablet', 'bottle', 'multivitamin', 'Vitamins & Supplements', false, false, true, 2.0, 5.0, 'Strip of 10', 10),
('Multivitamin 60mls', NULL, NULL, 'Tablet', 'bottle', 'multivitamin', 'Vitamins & Supplements', false, false, true, 2.0, 5.0, 'Strip of 10', 10),
('Multivitamin tabs', NULL, NULL, 'Tablet', 'tablet', 'multivitamin', 'Vitamins & Supplements', false, false, true, 2.0, 5.0, 'Strip of 10', 10),
('Neurocare plus', NULL, NULL, 'Capsule', 'capsule', 'neurocare', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Neuroforte', NULL, NULL, 'Tablet', 'tablet', 'neuroforte', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Neuropower', NULL, NULL, 'Tablet', 'tablet', 'neuropower', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Neurorubine forte', NULL, NULL, 'Tablet', 'tablet', 'vitamin b complex', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Nutrivita 100mls', NULL, NULL, 'Syrup', 'bottle', 'nutrivita', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Osteocare tabs', NULL, NULL, 'Tablet', 'tablet', 'osteocare', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Pregnacare conception pkts', 'Pregnacare', NULL, 'Tablet', 'packet', 'pregnacare conception pkts', 'Vitamins & Supplements', false, false, true, 700.0, 1200.0, 'Pack of 30', 1),
('Pregnacare original', 'Pregnacare', NULL, 'Tablet', 'packet', 'pregnacare original', 'Vitamins & Supplements', false, false, true, 700.0, 1200.0, 'Pack of 30', 1),
('Purecal', NULL, NULL, 'Syrup', 'bottle', 'purecal', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Pyridoxine', NULL, '50mg', 'Tablet', 'tablet', 'pyridoxine', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Ranferon caps', NULL, NULL, 'Capsule', 'capsule', 'iron+folic', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Ranferon syrup', NULL, '100mg', 'Syrup', 'bottle', 'iron+folic', 'Vitamins & Supplements', false, false, true, 90.0, 180.0, 'Bottle 100ml', 1),
('Seven seas caps', 'Seven Seas', NULL, 'Capsule', 'capsule', 'seven seas', 'Vitamins & Supplements', false, false, true, 500.0, 900.0, 'Bottle of 60', 1),
('Seven seas syrup 100ml', 'Seven Seas', NULL, 'Syrup', 'bottle', 'seven seas', 'Vitamins & Supplements', false, false, true, 500.0, 900.0, 'Bottle of 60', 1),
('Tresonix 100mls', NULL, NULL, 'Syrup', 'bottle', 'tresonix', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Tribees forte', NULL, NULL, 'Tablet', 'tablet', 'vitamin b complex', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1),
('Vitamin B complex', NULL, NULL, 'Tablet', 'tablet', 'vitamin b complex', 'Vitamins & Supplements', false, false, true, 1.5, 4.0, 'Strip of 10', 10),
('Zedcal', NULL, NULL, 'Tablet', 'tablet', 'zedcal', 'Vitamins & Supplements', false, false, true, NULL, NULL, NULL, 1)
ON CONFLICT (name, strength, dosage_form) DO UPDATE SET
  brand_name             = COALESCE(EXCLUDED.brand_name, drug_catalog.brand_name),
  base_unit              = EXCLUDED.base_unit,
  generic_name           = EXCLUDED.generic_name,
  category               = EXCLUDED.category,
  is_controlled          = EXCLUDED.is_controlled,
  requires_prescription  = EXCLUDED.requires_prescription,
  is_otc                 = EXCLUDED.is_otc,
  default_cost_price     = COALESCE(EXCLUDED.default_cost_price, drug_catalog.default_cost_price),
  default_selling_price  = COALESCE(EXCLUDED.default_selling_price, drug_catalog.default_selling_price),
  default_pack_label     = COALESCE(EXCLUDED.default_pack_label, drug_catalog.default_pack_label),
  default_units_per_pack = EXCLUDED.default_units_per_pack;

-- Replace: drop the old synthetic-only rows (never enriched here → generic_name
-- still NULL) that no product references. Referenced rows are kept (FK-safe).
DELETE FROM drug_catalog dc
WHERE dc.generic_name IS NULL
  AND NOT EXISTS (SELECT 1 FROM product p WHERE p.catalog_id = dc.id);

-- Backfill generic_name onto existing products: prefer the linked catalogue row,
-- else derive from the product name (strip the strength) so related-products
-- works for inventory that predates this migration.
UPDATE product p SET generic_name = dc.generic_name
  FROM drug_catalog dc
  WHERE p.catalog_id = dc.id AND p.generic_name IS NULL AND dc.generic_name IS NOT NULL;

UPDATE product SET generic_name =
  NULLIF(lower(btrim(regexp_replace(name, '\d+\.?\d*\s*(mg|mcg|g|iu|%)', '', 'gi'))), '')
  WHERE generic_name IS NULL;

-- migrate:down
-- Data seed — no structural rollback (the column/view rollback lives in 014).
SELECT 1;
